export const WEATHER_IS_LOADING = 'WEATHER_IS_LOADING';

export const WEATHER_HAS_ERROR = 'WEATHER_HAS_ERROR';

export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';

export const WEATHER_NEW_REQUEST = 'WEATHER_NEW_REQUEST';

